app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/app
    username: rotina-batch
    password: rotina-batch

spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/rotina-batch
    username: rotina-batch
    password: rotina-batch
  batch:
    jdbc:
      initialize-schema: always

logging:
  config:
